### ISSUE TITLE
Error in the datapath,ryu.exception.OFPUnknownVersion: unknown version 0. What's this actually?

### ISSUE THREAD

**Issue by DarmJarlo** [osrg/ryu#179]
Error in the datapath 0000000000000001 from ('127.0.0.1', 39970)
hub: uncaught exception: Traceback (most recent call last):
  File "/home/.local/lib/python3.8/site-packages/ryu/lib/hub.py", line 60, in _launch
    return func(*args, **kwargs)
  File "/home/.local/lib/python3.8/site-packages/ryu/controller/controller.py", line 557, in datapath_connection_factory
    datapath.serve()
  File "/home/.local/lib/python3.8/site-packages/ryu/controller/controller.py", line 475, in serve
    self._recv_loop()
  File "/home/.local/lib/python3.8/site-packages/ryu/controller/controller.py", line 215, in deactivate
    method(self)
  File "/home/.local/lib/python3.8/site-packages/ryu/controller/controller.py", line 361, in _recv_loop
    msg = ofproto_parser.msg(
  File "/home/.local/lib/python3.8/site-packages/ryu/ofproto/ofproto_parser.py", line 64, in msg
    raise exception.OFPUnknownVersion(version=version)
ryu.exception.OFPUnknownVersion: unknown version 0

I have always this error, Did somebody ever meet it and can help? Thanks in advance

**Comment by rnapoli00** [comment]
Same error here
