### ISSUE TITLE
When attempting to run `ryu-manager --version` after installing Ryu in a virtual environment, the following ImportError occurs:   ImportError: cannot

### ISSUE THREAD

**Issue by engrabdinasir** [osrg/ryu#185]
### Issue Description:

When attempting to run `ryu-manager --version` after installing Ryu in a virtual environment, the following ImportError occurs:

ImportError: cannot

import name 'ALREADY_HANDLED' from 'eventlet.wsgi' (/path/to/eventlet/wsgi.py)
```

### Steps to Reproduce:

1. Create a virtual environment:

   
   python3 -m venv my_ryu_env
   

2. Activate the virtual environment:

   
   source my_ryu_env/bin/activate
   

3. Install Ryu and eventlet:

      pip install ryu eventlet==0.30.2
   

4. Attempt to run `ryu-manager --version`:

   ```bash
   ryu-manager --version
   ```

### Expected Behavior:

The `ryu-manager --version` command should display the Ryu version without any ImportError.

### Actual Behavior:

The ImportError occurs, preventing the successful execution of the command.

### Environment:

- Ryu Version: 4.34
- Python Version: 3.10.12
Operating System: ubunto 20.04 lte
- Virtual Environment: Yes

### Dependencies:

- eventlet==0.30.2

### Additional Information:

- The issue persists even after downgrading eventlet to version 0.30.2.
- Full traceback and error message are provided in the Steps to Reproduce.

### Attempts to Resolve:

1. Tried different versions of eventlet (0.33.3 and 0.30.2).
2. Checked community forums for similar issues (provide links).

### Reproducibility:

The issue is consistently reproducible.

**Comment by badcodebuilder** [comment]
This error has been mentioned in #166

**Comment by hikareem** [comment]
husham@DESKTOP-HUPU73B:~/ryu_project$ ryu-manager
Traceback (most recent call last):
  File "/home/husham/ryu_project/my_ryu_env/bin/ryu-manager", line 33, in <module>
    sys.exit(load_entry_point('ryu==4.34', 'console_scripts', 'ryu-manager')())
  File "/home/husham/ryu_project/my_ryu_env/bin/ryu-manager", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/husham/.pyenv/versions/3.10.9/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/home/husham/.pyenv/versions/3.10.9/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/husham/ryu_project/my_ryu_env/lib/python3.10/site-packages/ryu/cmd/manager.py", line 22, in <module>
    from ryu.lib import hub
  File "/home/husham/ryu_project/my_ryu_env/lib/python3.10/site-packages/ryu/lib/hub.py", line 30, in <module>
    import eventlet
  File "/home/husham/ryu_project/my_ryu_env/lib/python3.10/site-packages/eventlet/__init__.py", line 17, in <module>
    from eventlet import convenience
  File "/home/husham/ryu_project/my_ryu_env/lib/python3.10/site-packages/eventlet/convenience.py", line 7, in <module>
    from eventlet.green import socket
  File "/home/husham/ryu_project/my_ryu_env/lib/python3.10/site-packages/eventlet/green/socket.py", line 4, in <module>
    __import__('eventlet.green._socket_nodns')
  File "/home/husham/ryu_project/my_ryu_env/lib/python3.10/site-packages/eventlet/green/_socket_nodns.py", line 11, in <module>
    from eventlet import greenio
  File "/home/husham/ryu_project/my_ryu_env/lib/python3.10/site-packages/eventlet/greenio/__init__.py", line 3, in <module>
    from eventlet.greenio.base import *  # noqa
  File "/home/husham/ryu_project/my_ryu_env/lib/python3.10/site-packages/eventlet/greenio/base.py", line 32, in <module>
    socket_timeout = eventlet.timeout.wrap_is_timeout(socket.timeout)
  File "/home/husham/ryu_project/my_ryu_env/lib/python3.10/site-packages/eventlet/timeout.py", line 166, in wrap_is_timeout
    base.is_timeout = property(lambda _: True)
TypeError: cannot set 'is_timeout' attribute of immutable type 'TimeoutError'
husham@DESKTOP-HUPU73B:~/ryu_project$
